### ISSUE TITLE
check_result API

### ISSUE THREAD

**Issue by schloerke** [rstudio-education/grader#11]
Grader is going through some API changes in #10 .  Thank you all for your input and patience!

Two big motivations are at play: keep it simple (@garrettgman ), keep it clean (@wch ).

---------------------------------------------

After talking it through with @blairj09, I think we have a clean, simple solution for `check_result`.
* Two check object functions: `passes` and `fails`.  (These names do not class with `checkmate` or `testthat`.)
* `passes` and `fails` can take:
  * a Value - equivalent to `~ identical(., value)`
  * a Formula - Evaluate the formula with `.` representing the user result
    * By using a formula (purrrr style) with `.`, there is no non-standard evaluation trickery to understand (such as a random `ans` being available).  As long as we state that `.` is the user result, the validation can be processed however the user writes.
    * Should return `TRUE` / `FALSE`
    * Throwing will cause an error in computing (bad for author)
  * a Function that takes an user result argument
    * Should return `TRUE` / `FALSE`
    * Throwing will cause an error in computing (bad for author)
* Once an equality (against a value) is found or `TRUE` (from a formula / function) is returned, computation will stop.  The respective message will be displayed as a correct (`passes`) or incorrect (`fails`) result.
* `correct` or `incorrect` params will be the default message for any `passes` or `fails` that do not provide a message.  They will be `glue`ed with appropriate information.

Example:

```r
check_result(
  fails(5, "bad answer!"),
  fails(~ . == 5, "bad answer!"),
  fails(~ isTRUE(all.equal(., 5)), "bad answer!"),
  fails(~ . %in% c(5,7), "bad answer!"),
  fails(function(x) x == 5, "bad answer!"),
  fails(function(x) x == 5),
  fails(somepkg::some_method, "bad answer!"), # function(x) ...

  passes(4, "good answer!"),
  passes(~ . == 4, "good answer!"),
  passes(~ . %in% c(4,6), "good answer!"),
  passes(function(x) x == 4, "good answer!"),
  passes(function(x) x == 4),
  passes(somepkg::some_method, "good answer!"), # function(x) ...

  correct = "You got it right!",
  incorrect = "You got it wrong."
)
```

---------------------------------------------

`check_result` will be kept separate from `test_result`.  All tests will be executed for `test_result`. 
* `test_result` will take
  *  a `test` object which will only accept formulas or functions as defined above (no values).  The message supplied will be provided if any throw occurs.
  * a Formula - the thrown error will be reported
  * a Function - the thrown error will be reported
* `correct` and `incorrect` will be `glue`ed with appropriate information.

Example:
```r
test_result(

  ~ checkmate::assert_function(., args = "x"),
  test(~ checkmate::assert_function(., args = "x"), "Make sure to have an 'x' argument!"),
  somepkg::some_expectation, # function(x) ...
  pryr::partial(checkmate::assert_function, args = "x"),

  correct = "{num_correct} / {num_total} correct! {random_praise()}",
  incorrect = "{num_correct} / {num_total} correct. {random_encourage()}"
)
```

---------------------------------------------

Again, these are not set in stone... just a followup from discussions over the past 48 hrs.

cc @gvwilson

**Comment by schloerke** [comment]
Adjustments:
* Use `~`
  * Use both `.` and `.result` in the formula
* `fails` / `passes` -> `fail_if(test, message)` / `pass_if(test, message)`
* Add praise and encourage arguments.  
  * Use a global setting by default.  
  * If function, evaluate it with no args
  * If `FALSE` or `NULL`, set to `character(0)`.
* Add global option for setting `praise` and `encourage` args
* For glue statements:
  * correct = "{.praise} Correct! {.message}"
  *  incorrect = "Incorrect! {.message} {.encourage}"
  * `.result`
  * `.errors`
* Default messages
```r
  correct = "Correct! {.praise} {.message}"
  incorrect = "Incorrect! {.message} {.encourage}"
```

ex:
```r
check_result(
  pass_if(test  = ~ .result == 5, message "passing message"),

  correct = "Correct! {.praise} {.message}"
  incorrect = "Incorrect! {.message} {.encourage}"

# example
  incorrect = " {.result} is not the answer! {.message} { random_encourage() }"


  # "you got it right! passing message 'Yay!'",
  praise = getOption("grader_praise", random_praise),
  encourage = getOption("grader_encourage", random_encourage),
  encourage = FALSE
)
```

**Comment by andrie** [comment]
My intent with `parsons` is to follow similar (if not identical) rules.

https://github.com/rstudio/parsons/issues/3
