### ISSUE TITLE
What is Dan's role?

### ISSUE THREAD

**Issue by chendaniely** [rstudio-education/grader#39]
`aut`? `ctb`? huh?

**Comment by schloerke** [comment]
https://www.loc.gov/marc/relators/relaterm.html

My thought...
Dan - `aut`
Barret - `aut`, `cre` 
Garrett - `aut`, `ccp`
RStudio - `cph`, `fnd`

(CRAN uses `cre` as maintainer.  I've used `ccp` (Conceptor) to recognize original author.)

While I'd like for you to be the maintainer, it is much smoother post internship for me or garrett to be maintainer. So, we can label you as first author in the description.
